#!/bin/bash

echo "> Downloading latest playit-agent binary..."
curl -sL "https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64" -o playit
chmod +x playit
sudo mv playit /usr/local/bin/playit
echo "> Playit.gg Installation Completed!"
echo "> Type 'playit' or running command: './startserver' to run playit host"
