#!/usr/bin/env bash
set -e

BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

echo "> Downloading Playit daemon..."
curl -fL \
    "https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64" \
    -o "$BIN_DIR/playitd"

echo "> Downloading Playit CLI..."
curl -fL \
    "https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-cli-linux-amd64" \
    -o "$BIN_DIR/playit"

chmod +x "$BIN_DIR/playitd"
chmod +x "$BIN_DIR/playit"

echo "> Playit.gg installation completed."