#!/bin/bash

export MAIN_DIR=$PWD
export JAVA=$MAIN_DIR/bin/java_bins/bin/java

cd "$MAIN_DIR/server" || exit 1

mem=$(grep MemTotal /proc/meminfo | sed -e 's/MemTotal:[ ]*//' | sed -e 's/ kB//')
mem_total=$((mem / 1024 / 1024))
mem=$((mem_total - 1))

if [ "$mem" -lt 1 ]; then
    mem=1
fi

if [ -f "fabric-server-launch.jar" ]; then
    SERVER_JAR="fabric-server-launch.jar"
else
    SERVER_JAR="server.jar"
fi

exec "$JAVA" -Xmx${mem}G -Xms${mem}G -jar "$SERVER_JAR" nogui