#!/usr/bin/env bash

echo "> Stopping mchost sessions..."

screen -S server -X quit 2>/dev/null || true
screen -S playit -X quit 2>/dev/null || true
screen -S afk -X quit 2>/dev/null || true

echo "> Server terminated!"
echo "> Run './startserver' to start it again."
echo "> Run './uninstall' if you want to remove the installed server."
